# docker.yml
---
- hosts: localhost
  become: true

  tasks:
    - block:
        - name: Install aptitude using apt
          apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

        - name: Install required system packages
          apt: name={{ item }} state=latest update_cache=yes
          loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

        - name: Add Docker GPG apt Key
          apt_key:
             url: https://download.docker.com/linux/ubuntu/gpg
             state: present

        - name: Add Docker Repository
          apt_repository:
             repo: deb https://download.docker.com/linux/ubuntu bionic stable
             state: present

        - name: Update apt and install docker-ce
          apt: update_cache=yes name=docker-ce state=latest

        - name: Install Docker Module for Python
          pip:
            name: docker

        - name: Docker group
          shell: |
                 sudo groupadd docker
                 sudo usermod -aG docker $USER
                 sudo systemctl enable docker

      rescue:
        - name: You need to recover
          debug:
            msg: "It looks like PIP is not installed. You will need to install it"

        - name: Recovery block
          shell: |
            sudo apt update
            sudo apt install python3-pip